/*
 * This source file was generated by the Gradle 'init' task
 */
package assessmentfinal;

import java.util.*;

public class App {
    static Scanner in;
    public static void main(String[] args) {
        in = new Scanner(System.in);
        Game game = new Game();
        String playerNames[] = new String[2];
        int choice = 0;

        do {
            try {
                System.out.print("Welcome to the Plant Species Database\n" +
                        "1) Add Plant Species\n" +
                        "2) Edit Species Entry\n" +
                        "3) Remove Plant Species\n" +
                        "4) Display Species Database\n" +
                        ">> ");

                choice = in.nextInt();
                in.nextLine(); // Consume newline

                switch (choice) {
                    case 1:
                        System.out.println("Starting a new game...");
                        for (int i = 0; i < playerNames.length; i++) {
                            System.out.println("Enter name for Player " + (i + 1) + "\n" + ">> ");
                            playerNames[i] = in.nextLine();
                        }

                        if (!game.startNewGame(playerNames)) {
                            System.out.println("Failed to start a new game.");
                            break;
                        }

                        game.turn();
                        break;
                    case 2:
                        if (!game.getSavedGamesList()) {
                            System.out.println("No saved games to load.");
                        }
                        System.out.println();

                        System.out.print("Enter the saved game to load\n" + ">> ");
                        String filename = in.next();
                        if (!game.loadPreviousGame(filename)) {
                            System.out.println("Failed to load the game.");
                            break;
                        }
                        break;
                    case 3:
                        System.out.println("How to play the game:");
                        break;
                    case 4:
                        choice = -1;
                        break;
                    default:
                        System.out.println("Invalid option");
                }
            } catch (InputMismatchException e) { // Catches invalid input (i.e. Strings/Chars)
                System.out.println("Invalid Input");
                in.next();
                clearScreen();
            } catch (NoSuchElementException e) { // Catches errors when there is no input passed
                System.out.println("Error reading input");
                clearScreen();
            } catch (Exception e) { // In the unlikely event you happen to pass an error that is neither of the above
                System.out.println("Now how in the hell did you get this?: " + e.getMessage());
                clearScreen();
            }
        } while (choice != -1);
        System.out.println("Exiting the application.");
        in.close();
    }

    /**
     * Clears the console
     */
    static void clearScreen() {
        if (in.hasNextLine()) {
            @SuppressWarnings("unused")
            String leftover = in.nextLine();
        }
        System.out.println("Press Enter to continue...");
        in.nextLine();
        System.out.print("\033[H\033[2J");
        System.out.flush();
    }
}
