/*
 * This source file was generated by the Gradle 'init' task
 */
package assessmentA;

import java.util.*;

public class App {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        plantSpeciesDB db = new plantSpeciesDB();
        int choice = 0;
        do {
            System.out.print("Welcome to the Plant Species Database\n" +
                    "1) Add Plant Species\n" +
                    "2) Rename Playlist\n" +
                    "3) Remove Playlist\n" +
                    "4) Display Species Database\n" +
                    "5) Search Database\n" +
                    "6) Edit Song\n" +
                    "7) Remove Song\n" +
                    "8) Sort Playlist\n" +
                    "9) Exit\n" +
                    ">> ");

                    choice = in.nextInt();

                    switch (choice) {
                        case 1:
                            
                            break;
                        case 5:
                            String search;
                            String sort;
                            System.out.print("Search by: Name, Region, Length, Width\n" + ">> ");
                            search = in.next();
                            System.out.print("Asc (a) or Desc (b)");
                            sort = in.next();

                            db.displayByOrder(sort, search);
                            break;
                        default:
                            break;
                    }
        } while (choice != -1);
    }
}